### ISSUE TITLE
how to use something like ".bind_tools" method in LangGraph?

### ISSUE THREAD

**Issue by a251746843** [kenual/langChain-llm-gpt4free#1]
how to use something like ".bind_tools" method in LangChain?
it needs to initialize an ChatOpenAI object and then use the “.bind_tools” method like the following codes: 
from langchain_core.tools import tool
@tool
def multiply(first_number: int, second_number: int):
    """Multiplies two numbers together."""
    return first_number * second_number
model = ChatOpenAI(temperature=0)
model_with_tools = model.bind_tools([multiply])

**Comment by kenual** [comment]
Please take a look at this LangChain issue  - https://github.com/langchain-ai/langchain/discussions/18591
